export interface ModuleInfo {
  key: string;
  number: number;
  title: string;
  description: string;
  route: string;
  color: string;
  active: boolean;
  estimatedMinutes: number;
  prerequisites: string[];
  storyGroup: "core" | "lab";
  storyOrder: number;
  storyRole: string;
  storyBefore: string;
  storyNow: string;
  storyNext: string;
  nextModuleKey: string | null;
  previousModuleKey: string | null;
  sidebarLabelShort: string;
  landingCta: string;
  storyRecap: string;
}

export const MODULES: ModuleInfo[] = [
  {
    key: "hash",
    number: 1,
    title: "Hash Playground",
    description: "SHA-256 and SHA-256d — type anything, watch the fingerprint materialize.",
    route: "/hash",
    color: "#F7931A",
    active: true,
    estimatedMinutes: 10,
    prerequisites: [],
    storyGroup: "core",
    storyOrder: 1,
    storyRole: "Chapter 1 of 7",
    storyBefore: "Start of the story.",
    storyNow: "Learn how Bitcoin creates irreversible fingerprints from any input.",
    storyNext: "Those fingerprints help build keys, addresses, and IDs.",
    nextModuleKey: "keys",
    previousModuleKey: null,
    sidebarLabelShort: "Hash",
    landingCta: "Start with fingerprints",
    storyRecap: "You learned that SHA-256 creates a unique 256-bit fingerprint for any input.",
  },
  {
    key: "keys",
    number: 2,
    title: "Keys & Addresses",
    description: "Generate a private key, derive public key, and encode Bitcoin addresses.",
    route: "/keys",
    color: "#36CFC9",
    active: true,
    estimatedMinutes: 15,
    prerequisites: ["hash"],
    storyGroup: "core",
    storyOrder: 2,
    storyRole: "Chapter 2 of 7",
    storyBefore: "Hashes create deterministic fingerprints.",
    storyNow: "Turn entropy into private keys, public keys, and addresses.",
    storyNext: "Those addresses will control spendable coins as UTXOs.",
    nextModuleKey: "utxo",
    previousModuleKey: "hash",
    sidebarLabelShort: "Keys",
    landingCta: "Turn entropy into keys",
    storyRecap: "You turned random entropy into a private key, public key, and Bitcoin address.",
  },
  {
    key: "utxo",
    number: 3,
    title: "UTXO & Transactions",
    description: "Build and inspect raw Bitcoin transactions, input by input.",
    route: "/utxo",
    color: "#7DD3FC",
    active: true,
    estimatedMinutes: 20,
    prerequisites: ["keys"],
    storyGroup: "core",
    storyOrder: 3,
    storyRole: "Chapter 3 of 7",
    storyBefore: "Keys define ownership.",
    storyNow: "Learn how Bitcoin represents coins as spendable outputs and builds transactions.",
    storyNext: "Those transactions are grouped into blocks and secured by mining.",
    nextModuleKey: "blockchain",
    previousModuleKey: "keys",
    sidebarLabelShort: "UTXO",
    landingCta: "Build a transaction",
    storyRecap: "You built a transaction that consumes old outputs and creates new ones.",
  },
  {
    key: "blockchain",
    number: 4,
    title: "Blockchain & Mining",
    description: "Mine blocks, adjust difficulty, and see how the chain grows.",
    route: "/blockchain",
    color: "#22C55E",
    active: true,
    estimatedMinutes: 20,
    prerequisites: ["utxo"],
    storyGroup: "core",
    storyOrder: 4,
    storyRole: "Chapter 4 of 7",
    storyBefore: "Transactions move value between outputs.",
    storyNow: "See how transactions become blocks linked by proof of work.",
    storyNext: "Then zoom back out to wallet structure and derived key trees.",
    nextModuleKey: "hd-wallet",
    previousModuleKey: "utxo",
    sidebarLabelShort: "Blockchain",
    landingCta: "Mine the next block",
    storyRecap: "You mined blocks and saw how proof of work secures the chain.",
  },
  {
    key: "hd-wallet",
    number: 5,
    title: "HD Wallet Tree",
    description: "BIP-32/39 hierarchical deterministic key derivation visualized.",
    route: "/hd-wallet",
    color: "#FBBF24",
    active: true,
    estimatedMinutes: 20,
    prerequisites: ["keys"],
    storyGroup: "core",
    storyOrder: 5,
    storyRole: "Chapter 5 of 7",
    storyBefore: "One key can control one address.",
    storyNow: "Scale that idea into a full wallet tree from one seed phrase.",
    storyNext: "Then use multiple keys together in a multisig policy.",
    nextModuleKey: "multisig",
    previousModuleKey: "blockchain",
    sidebarLabelShort: "HD Wallet",
    landingCta: "Grow one seed into a tree",
    storyRecap: "You derived an entire key tree from a single seed phrase.",
  },
  {
    key: "multisig",
    number: 6,
    title: "Multisig Vault",
    description: "Create 2-of-3 multisig scripts and sign with PSBTs.",
    route: "/multisig",
    color: "#A78BFA",
    active: true,
    estimatedMinutes: 25,
    prerequisites: ["keys", "utxo"],
    storyGroup: "core",
    storyOrder: 6,
    storyRole: "Chapter 6 of 7",
    storyBefore: "HD wallets organize many keys.",
    storyNow: "Combine keys into a shared spending policy and coordinate signatures with PSBT.",
    storyNext:
      "Now see how a single descriptor string encodes any wallet's keys, paths, and script type.",
    nextModuleKey: "descriptors",
    previousModuleKey: "hd-wallet",
    sidebarLabelShort: "Multisig",
    landingCta: "Coordinate shared custody",
    storyRecap: "You combined multiple keys into a shared spending policy with PSBT.",
  },
  {
    key: "descriptors",
    number: 7,
    title: "Output Descriptors",
    description:
      "Parse, expand, and build wallet descriptors — the portable language for any Bitcoin wallet.",
    route: "/descriptors",
    color: "#60A5FA",
    active: true,
    estimatedMinutes: 20,
    prerequisites: ["hd-wallet", "multisig"],
    storyGroup: "core",
    storyOrder: 7,
    storyRole: "Chapter 7 of 7",
    storyBefore: "HD wallets derive key trees; multisig combines keys into policies.",
    storyNow:
      "See how a single descriptor string encodes any wallet's keys, paths, and script type.",
    storyNext: "Explore failure modes in the Attack Lab, or return to any chapter.",
    nextModuleKey: null,
    previousModuleKey: "multisig",
    sidebarLabelShort: "Descriptors",
    landingCta: "Decode wallet descriptors",
    storyRecap:
      "You parsed, expanded, and built output descriptors that encode complete wallet strategies.",
  },
  {
    key: "attacks",
    number: 8,
    title: "Attack Lab",
    description: "Nonce reuse, xpub leaks, and other real-world crypto pitfalls.",
    route: "/attacks",
    color: "#FF6B6B",
    active: true,
    estimatedMinutes: 15,
    prerequisites: [],
    storyGroup: "lab",
    storyOrder: 1,
    storyRole: "Side Lab",
    storyBefore: "You've seen how Bitcoin is supposed to work.",
    storyNow:
      "This lab shows what breaks when entropy, derivation, signing, or transaction rules are misused.",
    storyNext: "Return to any chapter to connect each attack to the normal flow.",
    nextModuleKey: null,
    previousModuleKey: null,
    sidebarLabelShort: "Attacks",
    landingCta: "Explore failure modes",
    storyRecap: "You explored what happens when cryptographic best practices are violated.",
  },
];

/** Modules in the concept chain (excludes Attack Lab which is a standalone lab) */
export const LEARNING_PATH: string[] = [
  "hash",
  "keys",
  "utxo",
  "blockchain",
  "hd-wallet",
  "multisig",
  "descriptors",
];
